---
title: "Globally intercepting uncaught exceptions"
date: 21-07-23 14:26
tags: 
  - nodejs
  - errors
---

# Globally intercepting uncaught exceptions

It is possible to run functions when a certain exception is uncaught using the `process` object,
which is an instance of `EventEmitter`:
```javascript
const logger = require('./lib/logger.js')
process.on('uncaughtException', (err) => {
  logger.send("An uncaught exception occurred:", err, () => { 
    console.error(err);
    process.exit(1);
  })
})
```
In the example above, it runs a logger.
